### PR TITLE
Splitted the invitation handler and CS

### LINKED ISSUE #32: [RFC] Split InviteHandler into InviteHandler and ResendInvitationHandler
This will make it more explicit and avoid side effects and unexpected behavior when using `InviteHandler`

### PR DESCRIPTION
**Pull request by benatespina**
Closes #32

### CODE REVIEW

**Comment by gorkalaucirica** [comment]
Looks great to me but we now are missing an event in `$user->regenerateInvitationToken()` and therefore no emails can be sent with new token. Maybe we can merge this and add that feature in a new PR

**Comment by benatespina** [comment]
Yes... can we publish `UserInvited` event inside `regenerateInvitationToken` or we need an other custom event??

**Comment by gorkalaucirica** [comment]
Maybe we need another one, they are different use cases. I'm merging this and i will open an issue if you agree

**Comment by benatespina** [comment]
Not yet, we need to publish the UserInvited inside regenerateInvitationToken

**Pull request merged**
